[project]
name = "ai-tutorial-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "corner>=2.2.3",
    "jupyter>=1.1.1",
    "jupyterlab-rise>=0.43.1",
    "jupytext>=1.17.3",
    "kaleido>=1.1.0",
    "matplotlib>=3.9.4",
    "nbconvert>=7.16.6",
    "nbstripout>=0.8.1",
    "numpy>=2.0.2",
    "optuna>=4.5.0",
    "optuna-dashboard>=0.19.0",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
    "rise>=5.7.1",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "tensorflow>=2.20.0",
    "torch>=2.8.0",
]
